// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: dist/proto/comm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HTTP_CODE int32

const (
	HTTP_CODE_HTTP_CODE_SUCCESS      HTTP_CODE = 0
	HTTP_CODE_HTTP_CODE_ERROR        HTTP_CODE = 1
	HTTP_CODE_HTTP_CODE_EXISTED      HTTP_CODE = 2
	HTTP_CODE_HTTP_CODE_NOT_FOUND    HTTP_CODE = 3
	HTTP_CODE_HTTP_CODE_WRONG_FORMAT HTTP_CODE = 4
)

// Enum value maps for HTTP_CODE.
var (
	HTTP_CODE_name = map[int32]string{
		0: "HTTP_CODE_SUCCESS",
		1: "HTTP_CODE_ERROR",
		2: "HTTP_CODE_EXISTED",
		3: "HTTP_CODE_NOT_FOUND",
		4: "HTTP_CODE_WRONG_FORMAT",
	}
	HTTP_CODE_value = map[string]int32{
		"HTTP_CODE_SUCCESS":      0,
		"HTTP_CODE_ERROR":        1,
		"HTTP_CODE_EXISTED":      2,
		"HTTP_CODE_NOT_FOUND":    3,
		"HTTP_CODE_WRONG_FORMAT": 4,
	}
)

func (x HTTP_CODE) Enum() *HTTP_CODE {
	p := new(HTTP_CODE)
	*p = x
	return p
}

func (x HTTP_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTP_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_dist_proto_comm_proto_enumTypes[0].Descriptor()
}

func (HTTP_CODE) Type() protoreflect.EnumType {
	return &file_dist_proto_comm_proto_enumTypes[0]
}

func (x HTTP_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTTP_CODE.Descriptor instead.
func (HTTP_CODE) EnumDescriptor() ([]byte, []int) {
	return file_dist_proto_comm_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    HTTP_CODE `protobuf:"varint,1,opt,name=code,proto3,enum=Comm.HTTP_CODE" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_proto_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_dist_proto_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_dist_proto_comm_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() HTTP_CODE {
	if x != nil {
		return x.Code
	}
	return HTTP_CODE_HTTP_CODE_SUCCESS
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PageFilter) Reset() {
	*x = PageFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_proto_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageFilter) ProtoMessage() {}

func (x *PageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dist_proto_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageFilter.ProtoReflect.Descriptor instead.
func (*PageFilter) Descriptor() ([]byte, []int) {
	return file_dist_proto_comm_proto_rawDescGZIP(), []int{1}
}

func (x *PageFilter) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageFilter) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dist_proto_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dist_proto_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dist_proto_comm_proto_rawDescGZIP(), []int{2}
}

var File_dist_proto_comm_proto protoreflect.FileDescriptor

var file_dist_proto_comm_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x43, 0x6f, 0x6d, 0x6d, 0x22, 0x49, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x2e, 0x48,
	0x54, 0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x2a, 0x83, 0x01, 0x0a, 0x09, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x15,
	0x0a, 0x11, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x54,
	0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x17, 0x0a, 0x13, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x48, 0x54,
	0x54, 0x50, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x5f, 0x46, 0x4f,
	0x52, 0x4d, 0x41, 0x54, 0x10, 0x04, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dist_proto_comm_proto_rawDescOnce sync.Once
	file_dist_proto_comm_proto_rawDescData = file_dist_proto_comm_proto_rawDesc
)

func file_dist_proto_comm_proto_rawDescGZIP() []byte {
	file_dist_proto_comm_proto_rawDescOnce.Do(func() {
		file_dist_proto_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_dist_proto_comm_proto_rawDescData)
	})
	return file_dist_proto_comm_proto_rawDescData
}

var file_dist_proto_comm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dist_proto_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dist_proto_comm_proto_goTypes = []interface{}{
	(HTTP_CODE)(0),     // 0: Comm.HTTP_CODE
	(*Response)(nil),   // 1: Comm.Response
	(*PageFilter)(nil), // 2: Comm.PageFilter
	(*Empty)(nil),      // 3: Comm.Empty
}
var file_dist_proto_comm_proto_depIdxs = []int32{
	0, // 0: Comm.Response.code:type_name -> Comm.HTTP_CODE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dist_proto_comm_proto_init() }
func file_dist_proto_comm_proto_init() {
	if File_dist_proto_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dist_proto_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_proto_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dist_proto_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dist_proto_comm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dist_proto_comm_proto_goTypes,
		DependencyIndexes: file_dist_proto_comm_proto_depIdxs,
		EnumInfos:         file_dist_proto_comm_proto_enumTypes,
		MessageInfos:      file_dist_proto_comm_proto_msgTypes,
	}.Build()
	File_dist_proto_comm_proto = out.File
	file_dist_proto_comm_proto_rawDesc = nil
	file_dist_proto_comm_proto_goTypes = nil
	file_dist_proto_comm_proto_depIdxs = nil
}
